apiVersion: v1
kind: Service
metadata:
  name: zalenium
  namespace: zalenium
spec:
  type: LoadBalancer
  loadBalancerIP: "35.201.93.162"
  sessionAffinity: None
  ports:
    - name: zalenium
      protocol: TCP
      port: 4444
      targetPort: 7777
  selector:
    zalenium: hub
